"""add last_answered_index to room_players col

Revision ID: 79c92c0025ac
Revises: d26cc0a1f88d
Create Date: 2026-10-03 11:29:55.453143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c92c0025ac'
down_revision: Union[str, Sequence[str], None] = 'd26cc0a1f88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('room_players', sa.Column('last_answered_index', sa.Integer(), server_default='-1', nullable=False))
    op.alter_column('student_registry', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_registry', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('room_players', 'last_answered_index')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
