"""add student_registry table + roll_no altered to String type

Revision ID: d26cc0a1f88d
Revises: f6cf53079ed5
Create Date: 2026-09-26 17:57:43.339558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26cc0a1f88d'
down_revision: Union[str, Sequence[str], None] = 'f6cf53079ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_registry',
    sa.Column('roll_no', sa.String(length=50), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('roll_no')
    )
    op.alter_column('players', 'roll_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'roll_no',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('student_registry')
    # ### end Alembic commands ###
