"""addd fk to col roll_no linked to student_registy.roll_no

Revision ID: dfaac8761917
Revises: d26cc0a1f88d
Create Date: 2026-09-27 12:09:41.782292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfaac8761917'
down_revision: Union[str, Sequence[str], None] = 'd26cc0a1f88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'players', 'student_registry', ['roll_no'], ['roll_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'players', type_='foreignkey')
    # ### end Alembic commands ###
